theme = "transparent"

[editor]
line-number = "relative"
mouse = true
idle-timeout = 10
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-y = [
	':sh rm -f /tmp/unique-ca1ea106',
	':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-ca1ea106',
	':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
	':open %sh{cat /tmp/unique-ca1ea106}',
	':redraw',
	':set mouse false',
  ':set mouse true',
]

