[tools]
bun = "latest"
cargo-binstall = "latest"
"cargo:eza" = "latest"
"cargo:starship" = "latest"
"cargo:zellij" = "latest"
chezmoi = "2.71.0"
colima = "latest"
dotnet = "latest"
go = "latest"
node = "latest"
"npm:@typescript/native-preview" = "latest"
opencode = "latest"
rust = "latest"
uv = "latest"
watchexec = "latest"
yazi = "latest"
zoxide = "latest"
